version: '3.8'
services:
  camera-server:
    build:
      context: .
      dockerfile: tcp_ip/Dockerfile
    container_name: camera-server
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"
    cap_add:
      - SYS_ADMIN
